# AndroidX
android.useAndroidX=true
# Désactive Jetifier si TOUTES tes deps sont AndroidX (recommandé). Sinon remets true.
android.enableJetifier=true

# Gradle en CI
org.gradle.daemon=false
org.gradle.workers.max=1
org.gradle.jvmargs=-Xmx3g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError

# Caching
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.vfs.watch=false

# Kotlin compiler daemon
kotlin.daemon.jvmargs=-Xmx1g -XX:MaxMetaspaceSize=512m
