android.useAndroidX=true
android.enableJetifier=true

org.gradle.daemon=false
org.gradle.workers.max=1
org.gradle.jvmargs=-Xmx3g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError

org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.vfs.watch=false

kotlin.daemon.jvmargs=-Xmx1g -XX:MaxMetaspaceSize=512m
